version: '3.8'

services:
  # 1. СЕРВИС ГРАФА ЗНАНИЙ (Knowledge Graph - Neo4j)
  neo4j:
    image: neo4j:latest
    container_name: neo4j-knowledge-graph
    ports:
      - "7474:7474" # HTTP/Browser UI
      - "7687:7687" # Bolt Protocol (для Python-клиента)
    environment:
      NEO4J_AUTH: neo4j/test12345
      # NEO4J_db_mode: HA
    volumes:
      - ./data/neo4j:/data
      - ./logs/neo4j:/logs
  
  neo4j2:
    image: neo4j:latest
    container_name: neo4j-knowledge-graph2
    ports:
      - "7475:7474" # HTTP/Browser UI
      - "7689:7687" # Bolt Protocol (для Python-клиента)
    environment:
      NEO4J_AUTH: neo4j/test12345
      # NEO4J_db_mode: HA
    volumes:
      - ./data2/neo4j:/data
      - ./logs2/neo4j:/logs

  # 2. СЕРВИС ВЕКТОРНОГО ХРАНИЛИЩА (Vector Store - Weaviate)
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
    restart: unless-stopped